// ============================================================
// 이상형 월드컵 후보 데이터
// ============================================================
// 이 배열 안의 항목을 자유롭게 추가 / 삭제 / 수정하세요.
// 앱 로직(script.js)은 절대 건드릴 필요 없이, 이 파일만 고치면 됩니다.
//
// [필드 설명]
//   id        : 다른 항목과 겹치지 않는 고유 값 (자유롭게 작성 가능)
//   name      : 화면에 표시될 이름
//   group     : 소속 그룹 (표시용, 없으면 "" 로 비워두면 됨)
//   gender    : "female" 또는 "male" 만 사용 — 이 값으로 여돌/남돌을 구분합니다
//   youtubeId : 유튜브 영상 주소의 v= 뒤에 오는 11자리 코드
//               예) https://www.youtube.com/watch?v=dQw4w9WgXcQ  ->  dQw4w9WgXcQ
//               (유튜브 앱/사이트에서 "공유 > 링크 복사"로 받은 짧은 주소 youtu.be/XXXXXXXXXXX 의
//                XXXXXXXXXXX 부분도 동일한 코드입니다)
//   start     : 영상이 몇 초부터 재생될지 (직캠 하이라이트 구간부터 보여주고 싶을 때 사용, 기본 0)
//
// ⚠️  아래 데이터는 전부 예시(placeholder)입니다. 실제 직캠으로 교체해서 사용하세요.
//     이름/그룹은 자리표시자이고, youtubeId는 재생 확인용 임의의 공개 영상입니다.
// ============================================================

const CANDIDATES = [
  { id: "f001", name: "여자 아이돌 01", group: "그룹명 예시", gender: "female", youtubeId: "dQw4w9WgXcQ", start: 0 },
  { id: "f002", name: "여자 아이돌 02", group: "그룹명 예시", gender: "female", youtubeId: "jNQXAC9IVRw", start: 0 },
  { id: "f003", name: "여자 아이돌 03", group: "그룹명 예시", gender: "female", youtubeId: "9bZkp7q19f0", start: 0 },
  { id: "f004", name: "여자 아이돌 04", group: "그룹명 예시", gender: "female", youtubeId: "kJQP7kiw5Fk", start: 0 },
  { id: "f005", name: "여자 아이돌 05", group: "그룹명 예시", gender: "female", youtubeId: "OPf0YbXqDm0", start: 0 },
  { id: "f006", name: "여자 아이돌 06", group: "그룹명 예시", gender: "female", youtubeId: "dQw4w9WgXcQ", start: 0 },
  { id: "f007", name: "여자 아이돌 07", group: "그룹명 예시", gender: "female", youtubeId: "jNQXAC9IVRw", start: 0 },
  { id: "f008", name: "여자 아이돌 08", group: "그룹명 예시", gender: "female", youtubeId: "9bZkp7q19f0", start: 0 },
  { id: "f009", name: "여자 아이돌 09", group: "그룹명 예시", gender: "female", youtubeId: "kJQP7kiw5Fk", start: 0 },
  { id: "f010", name: "여자 아이돌 10", group: "그룹명 예시", gender: "female", youtubeId: "OPf0YbXqDm0", start: 0 },
  { id: "f011", name: "여자 아이돌 11", group: "그룹명 예시", gender: "female", youtubeId: "dQw4w9WgXcQ", start: 0 },
  { id: "f012", name: "여자 아이돌 12", group: "그룹명 예시", gender: "female", youtubeId: "jNQXAC9IVRw", start: 0 },
  { id: "f013", name: "여자 아이돌 13", group: "그룹명 예시", gender: "female", youtubeId: "9bZkp7q19f0", start: 0 },
  { id: "f014", name: "여자 아이돌 14", group: "그룹명 예시", gender: "female", youtubeId: "kJQP7kiw5Fk", start: 0 },
  { id: "f015", name: "여자 아이돌 15", group: "그룹명 예시", gender: "female", youtubeId: "OPf0YbXqDm0", start: 0 },
  { id: "f016", name: "여자 아이돌 16", group: "그룹명 예시", gender: "female", youtubeId: "dQw4w9WgXcQ", start: 0 },
  { id: "f017", name: "여자 아이돌 17", group: "그룹명 예시", gender: "female", youtubeId: "jNQXAC9IVRw", start: 0 },
  { id: "f018", name: "여자 아이돌 18", group: "그룹명 예시", gender: "female", youtubeId: "9bZkp7q19f0", start: 0 },
  { id: "f019", name: "여자 아이돌 19", group: "그룹명 예시", gender: "female", youtubeId: "kJQP7kiw5Fk", start: 0 },
  { id: "f020", name: "여자 아이돌 20", group: "그룹명 예시", gender: "female", youtubeId: "OPf0YbXqDm0", start: 0 },
  { id: "f021", name: "여자 아이돌 21", group: "그룹명 예시", gender: "female", youtubeId: "dQw4w9WgXcQ", start: 0 },
  { id: "f022", name: "여자 아이돌 22", group: "그룹명 예시", gender: "female", youtubeId: "jNQXAC9IVRw", start: 0 },
  { id: "f023", name: "여자 아이돌 23", group: "그룹명 예시", gender: "female", youtubeId: "9bZkp7q19f0", start: 0 },
  { id: "f024", name: "여자 아이돌 24", group: "그룹명 예시", gender: "female", youtubeId: "kJQP7kiw5Fk", start: 0 },
  { id: "f025", name: "여자 아이돌 25", group: "그룹명 예시", gender: "female", youtubeId: "OPf0YbXqDm0", start: 0 },
  { id: "f026", name: "여자 아이돌 26", group: "그룹명 예시", gender: "female", youtubeId: "dQw4w9WgXcQ", start: 0 },
  { id: "f027", name: "여자 아이돌 27", group: "그룹명 예시", gender: "female", youtubeId: "jNQXAC9IVRw", start: 0 },
  { id: "f028", name: "여자 아이돌 28", group: "그룹명 예시", gender: "female", youtubeId: "9bZkp7q19f0", start: 0 },
  { id: "f029", name: "여자 아이돌 29", group: "그룹명 예시", gender: "female", youtubeId: "kJQP7kiw5Fk", start: 0 },
  { id: "f030", name: "여자 아이돌 30", group: "그룹명 예시", gender: "female", youtubeId: "OPf0YbXqDm0", start: 0 },
  { id: "f031", name: "여자 아이돌 31", group: "그룹명 예시", gender: "female", youtubeId: "dQw4w9WgXcQ", start: 0 },
  { id: "f032", name: "여자 아이돌 32", group: "그룹명 예시", gender: "female", youtubeId: "jNQXAC9IVRw", start: 0 },
  { id: "f033", name: "여자 아이돌 33", group: "그룹명 예시", gender: "female", youtubeId: "9bZkp7q19f0", start: 0 },
  { id: "f034", name: "여자 아이돌 34", group: "그룹명 예시", gender: "female", youtubeId: "kJQP7kiw5Fk", start: 0 },
  { id: "f035", name: "여자 아이돌 35", group: "그룹명 예시", gender: "female", youtubeId: "OPf0YbXqDm0", start: 0 },
  { id: "f036", name: "여자 아이돌 36", group: "그룹명 예시", gender: "female", youtubeId: "dQw4w9WgXcQ", start: 0 },
  { id: "f037", name: "여자 아이돌 37", group: "그룹명 예시", gender: "female", youtubeId: "jNQXAC9IVRw", start: 0 },
  { id: "f038", name: "여자 아이돌 38", group: "그룹명 예시", gender: "female", youtubeId: "9bZkp7q19f0", start: 0 },
  { id: "f039", name: "여자 아이돌 39", group: "그룹명 예시", gender: "female", youtubeId: "kJQP7kiw5Fk", start: 0 },
  { id: "f040", name: "여자 아이돌 40", group: "그룹명 예시", gender: "female", youtubeId: "OPf0YbXqDm0", start: 0 },
  { id: "f041", name: "여자 아이돌 41", group: "그룹명 예시", gender: "female", youtubeId: "dQw4w9WgXcQ", start: 0 },
  { id: "f042", name: "여자 아이돌 42", group: "그룹명 예시", gender: "female", youtubeId: "jNQXAC9IVRw", start: 0 },
  { id: "f043", name: "여자 아이돌 43", group: "그룹명 예시", gender: "female", youtubeId: "9bZkp7q19f0", start: 0 },
  { id: "f044", name: "여자 아이돌 44", group: "그룹명 예시", gender: "female", youtubeId: "kJQP7kiw5Fk", start: 0 },
  { id: "f045", name: "여자 아이돌 45", group: "그룹명 예시", gender: "female", youtubeId: "OPf0YbXqDm0", start: 0 },
  { id: "f046", name: "여자 아이돌 46", group: "그룹명 예시", gender: "female", youtubeId: "dQw4w9WgXcQ", start: 0 },
  { id: "f047", name: "여자 아이돌 47", group: "그룹명 예시", gender: "female", youtubeId: "jNQXAC9IVRw", start: 0 },
  { id: "f048", name: "여자 아이돌 48", group: "그룹명 예시", gender: "female", youtubeId: "9bZkp7q19f0", start: 0 },
  { id: "f049", name: "여자 아이돌 49", group: "그룹명 예시", gender: "female", youtubeId: "kJQP7kiw5Fk", start: 0 },
  { id: "f050", name: "여자 아이돌 50", group: "그룹명 예시", gender: "female", youtubeId: "OPf0YbXqDm0", start: 0 },
  { id: "f051", name: "여자 아이돌 51", group: "그룹명 예시", gender: "female", youtubeId: "dQw4w9WgXcQ", start: 0 },
  { id: "f052", name: "여자 아이돌 52", group: "그룹명 예시", gender: "female", youtubeId: "jNQXAC9IVRw", start: 0 },
  { id: "f053", name: "여자 아이돌 53", group: "그룹명 예시", gender: "female", youtubeId: "9bZkp7q19f0", start: 0 },
  { id: "f054", name: "여자 아이돌 54", group: "그룹명 예시", gender: "female", youtubeId: "kJQP7kiw5Fk", start: 0 },
  { id: "f055", name: "여자 아이돌 55", group: "그룹명 예시", gender: "female", youtubeId: "OPf0YbXqDm0", start: 0 },
  { id: "f056", name: "여자 아이돌 56", group: "그룹명 예시", gender: "female", youtubeId: "dQw4w9WgXcQ", start: 0 },
  { id: "f057", name: "여자 아이돌 57", group: "그룹명 예시", gender: "female", youtubeId: "jNQXAC9IVRw", start: 0 },
  { id: "f058", name: "여자 아이돌 58", group: "그룹명 예시", gender: "female", youtubeId: "9bZkp7q19f0", start: 0 },
  { id: "f059", name: "여자 아이돌 59", group: "그룹명 예시", gender: "female", youtubeId: "kJQP7kiw5Fk", start: 0 },
  { id: "f060", name: "여자 아이돌 60", group: "그룹명 예시", gender: "female", youtubeId: "OPf0YbXqDm0", start: 0 },
  { id: "f061", name: "여자 아이돌 61", group: "그룹명 예시", gender: "female", youtubeId: "dQw4w9WgXcQ", start: 0 },
  { id: "f062", name: "여자 아이돌 62", group: "그룹명 예시", gender: "female", youtubeId: "jNQXAC9IVRw", start: 0 },
  { id: "f063", name: "여자 아이돌 63", group: "그룹명 예시", gender: "female", youtubeId: "9bZkp7q19f0", start: 0 },
  { id: "f064", name: "여자 아이돌 64", group: "그룹명 예시", gender: "female", youtubeId: "kJQP7kiw5Fk", start: 0 },
  { id: "m001", name: "남자 아이돌 01", group: "그룹명 예시", gender: "male", youtubeId: "OPf0YbXqDm0", start: 0 },
  { id: "m002", name: "남자 아이돌 02", group: "그룹명 예시", gender: "male", youtubeId: "dQw4w9WgXcQ", start: 0 },
  { id: "m003", name: "남자 아이돌 03", group: "그룹명 예시", gender: "male", youtubeId: "jNQXAC9IVRw", start: 0 },
  { id: "m004", name: "남자 아이돌 04", group: "그룹명 예시", gender: "male", youtubeId: "9bZkp7q19f0", start: 0 },
  { id: "m005", name: "남자 아이돌 05", group: "그룹명 예시", gender: "male", youtubeId: "kJQP7kiw5Fk", start: 0 },
  { id: "m006", name: "남자 아이돌 06", group: "그룹명 예시", gender: "male", youtubeId: "OPf0YbXqDm0", start: 0 },
  { id: "m007", name: "남자 아이돌 07", group: "그룹명 예시", gender: "male", youtubeId: "dQw4w9WgXcQ", start: 0 },
  { id: "m008", name: "남자 아이돌 08", group: "그룹명 예시", gender: "male", youtubeId: "jNQXAC9IVRw", start: 0 },
  { id: "m009", name: "남자 아이돌 09", group: "그룹명 예시", gender: "male", youtubeId: "9bZkp7q19f0", start: 0 },
  { id: "m010", name: "남자 아이돌 10", group: "그룹명 예시", gender: "male", youtubeId: "kJQP7kiw5Fk", start: 0 },
  { id: "m011", name: "남자 아이돌 11", group: "그룹명 예시", gender: "male", youtubeId: "OPf0YbXqDm0", start: 0 },
  { id: "m012", name: "남자 아이돌 12", group: "그룹명 예시", gender: "male", youtubeId: "dQw4w9WgXcQ", start: 0 },
  { id: "m013", name: "남자 아이돌 13", group: "그룹명 예시", gender: "male", youtubeId: "jNQXAC9IVRw", start: 0 },
  { id: "m014", name: "남자 아이돌 14", group: "그룹명 예시", gender: "male", youtubeId: "9bZkp7q19f0", start: 0 },
  { id: "m015", name: "남자 아이돌 15", group: "그룹명 예시", gender: "male", youtubeId: "kJQP7kiw5Fk", start: 0 },
  { id: "m016", name: "남자 아이돌 16", group: "그룹명 예시", gender: "male", youtubeId: "OPf0YbXqDm0", start: 0 },
  { id: "m017", name: "남자 아이돌 17", group: "그룹명 예시", gender: "male", youtubeId: "dQw4w9WgXcQ", start: 0 },
  { id: "m018", name: "남자 아이돌 18", group: "그룹명 예시", gender: "male", youtubeId: "jNQXAC9IVRw", start: 0 },
  { id: "m019", name: "남자 아이돌 19", group: "그룹명 예시", gender: "male", youtubeId: "9bZkp7q19f0", start: 0 },
  { id: "m020", name: "남자 아이돌 20", group: "그룹명 예시", gender: "male", youtubeId: "kJQP7kiw5Fk", start: 0 },
  { id: "m021", name: "남자 아이돌 21", group: "그룹명 예시", gender: "male", youtubeId: "OPf0YbXqDm0", start: 0 },
  { id: "m022", name: "남자 아이돌 22", group: "그룹명 예시", gender: "male", youtubeId: "dQw4w9WgXcQ", start: 0 },
  { id: "m023", name: "남자 아이돌 23", group: "그룹명 예시", gender: "male", youtubeId: "jNQXAC9IVRw", start: 0 },
  { id: "m024", name: "남자 아이돌 24", group: "그룹명 예시", gender: "male", youtubeId: "9bZkp7q19f0", start: 0 },
  { id: "m025", name: "남자 아이돌 25", group: "그룹명 예시", gender: "male", youtubeId: "kJQP7kiw5Fk", start: 0 },
  { id: "m026", name: "남자 아이돌 26", group: "그룹명 예시", gender: "male", youtubeId: "OPf0YbXqDm0", start: 0 },
  { id: "m027", name: "남자 아이돌 27", group: "그룹명 예시", gender: "male", youtubeId: "dQw4w9WgXcQ", start: 0 },
  { id: "m028", name: "남자 아이돌 28", group: "그룹명 예시", gender: "male", youtubeId: "jNQXAC9IVRw", start: 0 },
  { id: "m029", name: "남자 아이돌 29", group: "그룹명 예시", gender: "male", youtubeId: "9bZkp7q19f0", start: 0 },
  { id: "m030", name: "남자 아이돌 30", group: "그룹명 예시", gender: "male", youtubeId: "kJQP7kiw5Fk", start: 0 },
  { id: "m031", name: "남자 아이돌 31", group: "그룹명 예시", gender: "male", youtubeId: "OPf0YbXqDm0", start: 0 },
  { id: "m032", name: "남자 아이돌 32", group: "그룹명 예시", gender: "male", youtubeId: "dQw4w9WgXcQ", start: 0 },
  { id: "m033", name: "남자 아이돌 33", group: "그룹명 예시", gender: "male", youtubeId: "jNQXAC9IVRw", start: 0 },
  { id: "m034", name: "남자 아이돌 34", group: "그룹명 예시", gender: "male", youtubeId: "9bZkp7q19f0", start: 0 },
  { id: "m035", name: "남자 아이돌 35", group: "그룹명 예시", gender: "male", youtubeId: "kJQP7kiw5Fk", start: 0 },
  { id: "m036", name: "남자 아이돌 36", group: "그룹명 예시", gender: "male", youtubeId: "OPf0YbXqDm0", start: 0 },
  { id: "m037", name: "남자 아이돌 37", group: "그룹명 예시", gender: "male", youtubeId: "dQw4w9WgXcQ", start: 0 },
  { id: "m038", name: "남자 아이돌 38", group: "그룹명 예시", gender: "male", youtubeId: "jNQXAC9IVRw", start: 0 },
  { id: "m039", name: "남자 아이돌 39", group: "그룹명 예시", gender: "male", youtubeId: "9bZkp7q19f0", start: 0 },
  { id: "m040", name: "남자 아이돌 40", group: "그룹명 예시", gender: "male", youtubeId: "kJQP7kiw5Fk", start: 0 },
  { id: "m041", name: "남자 아이돌 41", group: "그룹명 예시", gender: "male", youtubeId: "OPf0YbXqDm0", start: 0 },
  { id: "m042", name: "남자 아이돌 42", group: "그룹명 예시", gender: "male", youtubeId: "dQw4w9WgXcQ", start: 0 },
  { id: "m043", name: "남자 아이돌 43", group: "그룹명 예시", gender: "male", youtubeId: "jNQXAC9IVRw", start: 0 },
  { id: "m044", name: "남자 아이돌 44", group: "그룹명 예시", gender: "male", youtubeId: "9bZkp7q19f0", start: 0 },
  { id: "m045", name: "남자 아이돌 45", group: "그룹명 예시", gender: "male", youtubeId: "kJQP7kiw5Fk", start: 0 },
  { id: "m046", name: "남자 아이돌 46", group: "그룹명 예시", gender: "male", youtubeId: "OPf0YbXqDm0", start: 0 },
  { id: "m047", name: "남자 아이돌 47", group: "그룹명 예시", gender: "male", youtubeId: "dQw4w9WgXcQ", start: 0 },
  { id: "m048", name: "남자 아이돌 48", group: "그룹명 예시", gender: "male", youtubeId: "jNQXAC9IVRw", start: 0 },
  { id: "m049", name: "남자 아이돌 49", group: "그룹명 예시", gender: "male", youtubeId: "9bZkp7q19f0", start: 0 },
  { id: "m050", name: "남자 아이돌 50", group: "그룹명 예시", gender: "male", youtubeId: "kJQP7kiw5Fk", start: 0 },
  { id: "m051", name: "남자 아이돌 51", group: "그룹명 예시", gender: "male", youtubeId: "OPf0YbXqDm0", start: 0 },
  { id: "m052", name: "남자 아이돌 52", group: "그룹명 예시", gender: "male", youtubeId: "dQw4w9WgXcQ", start: 0 },
  { id: "m053", name: "남자 아이돌 53", group: "그룹명 예시", gender: "male", youtubeId: "jNQXAC9IVRw", start: 0 },
  { id: "m054", name: "남자 아이돌 54", group: "그룹명 예시", gender: "male", youtubeId: "9bZkp7q19f0", start: 0 },
  { id: "m055", name: "남자 아이돌 55", group: "그룹명 예시", gender: "male", youtubeId: "kJQP7kiw5Fk", start: 0 },
  { id: "m056", name: "남자 아이돌 56", group: "그룹명 예시", gender: "male", youtubeId: "OPf0YbXqDm0", start: 0 },
  { id: "m057", name: "남자 아이돌 57", group: "그룹명 예시", gender: "male", youtubeId: "dQw4w9WgXcQ", start: 0 },
  { id: "m058", name: "남자 아이돌 58", group: "그룹명 예시", gender: "male", youtubeId: "jNQXAC9IVRw", start: 0 },
  { id: "m059", name: "남자 아이돌 59", group: "그룹명 예시", gender: "male", youtubeId: "9bZkp7q19f0", start: 0 },
  { id: "m060", name: "남자 아이돌 60", group: "그룹명 예시", gender: "male", youtubeId: "kJQP7kiw5Fk", start: 0 },
  { id: "m061", name: "남자 아이돌 61", group: "그룹명 예시", gender: "male", youtubeId: "OPf0YbXqDm0", start: 0 },
  { id: "m062", name: "남자 아이돌 62", group: "그룹명 예시", gender: "male", youtubeId: "dQw4w9WgXcQ", start: 0 },
  { id: "m063", name: "남자 아이돌 63", group: "그룹명 예시", gender: "male", youtubeId: "jNQXAC9IVRw", start: 0 },
  { id: "m064", name: "남자 아이돌 64", group: "그룹명 예시", gender: "male", youtubeId: "9bZkp7q19f0", start: 0 },
];
